server:
  port: 9001
  tomcat:
    connection-timeout: 2s  #defines a limit for how much time Tomcat should wait between accepting a TCP connection from a client and actually receiving the HTTP request
    keep-alive-timeout: 15s # configure how long to keep a connection open while waiting for new HTTP requests
    threads:
      max: 50
      min-spare: 5


